// The topic taxonomy.
//
// A field (lib/arxiv.ts) is a broad area such as "Computer Vision". A topic
// is a narrower theme inside a field, such as "3D vision" or "Medical
// imaging". Every paper gets up to three topics, chosen by lib/tagger.ts.
//
// Each topic carries:
//   - description: one or two sentences. Read by people as a tooltip and by
//     the embedding tagger, which compares it with the abstract.
//   - cats: arXiv categories that hint at the topic. A weak signal only:
//     cs.CL hints at every NLP topic, so it can never decide on its own.
//   - patterns: case-insensitive regular expressions matched against the
//     title and abstract. These decide the rule-based tags. Keep them
//     specific: a pattern that matches half of all papers is worse than none.
//   - query: the arXiv search used when a reader taps the topic. It is one
//     phrase because the API route wraps it as a single `all:` term.
//   - gated (optional): the topic only applies to papers that carry one of
//     its categories. Used where the vocabulary is shared with other areas,
//     for example "gait" (robot locomotion, but also gait recognition in
//     vision) or "replay" (memory in neuroscience, but also in RL and GPUs).
//   - minScore (optional): a higher bar than the default in lib/tagger.ts,
//     for topics whose single words are too common to trust on their own
//     ("benchmark", "safety", "LLM").
//
// To add a topic, append an entry. tests/unit/topics.test.ts checks that ids
// are unique, fields exist, and every pattern compiles.

import { FIELDS } from "@/lib/arxiv";

export type Topic = {
  id: string;
  label: string;
  field: string;
  description: string;
  cats: string[];
  patterns: string[];
  query: string;
  gated?: boolean;
  minScore?: number;
};

export const TOPICS: Topic[] = [
  // AI & Machine Learning -----------------------------------------------
  {
    id: "llms",
    label: "Large language models",
    field: "ai-ml",
    minScore: 3,
    description:
      "Large language models: pretraining, instruction tuning, prompting, in-context learning, and how these models behave and scale.",
    cats: ["cs.CL", "cs.LG", "cs.AI"],
    patterns: [
      "\\blarge language models?\\b",
      "\\bLLMs?\\b",
      "\\bGPT-?\\d",
      "\\binstruction[- ]tun",
      "\\bprompt(ing|s)?\\b",
      "\\bin-context learning\\b",
      "\\bchain[- ]of[- ]thought\\b",
      "\\bfoundation models?\\b",
    ],
    query: "large language model",
  },
  {
    id: "ai-agents",
    label: "AI agents",
    field: "ai-ml",
    description:
      "Systems where a model plans, calls tools, browses, or acts over several steps, alone or with other agents.",
    cats: ["cs.AI", "cs.MA"],
    patterns: [
      "\\bagentic\\b",
      "\\btool[- ](use|calling|augmented)\\b",
      "\\b(LLM|language model)[- ]based agents?\\b",
      "\\bmulti-?agent\\b",
      "\\bautonomous agents?\\b",
      "\\bweb agents?\\b",
    ],
    query: "agentic",
  },
  {
    id: "reinforcement-learning",
    label: "Reinforcement learning",
    field: "ai-ml",
    description:
      "Learning from rewards: policies, value functions, exploration, offline RL, and reward modelling.",
    cats: ["cs.LG", "cs.AI"],
    patterns: [
      "\\breinforcement learning\\b",
      "\\bpolicy (gradient|optimi[sz]ation|iteration)\\b",
      "\\bQ-learning\\b",
      "\\bMarkov decision process",
      "\\bPPO\\b",
      "\\breward (function|model|shaping|hacking)\\b",
      "\\boffline RL\\b",
      "\\bRL\\b",
    ],
    query: "reinforcement learning",
  },
  {
    id: "generative-models",
    label: "Generative models",
    field: "ai-ml",
    description:
      "Diffusion models, flows, GANs, and autoencoders: learning to sample new data that looks like the training data.",
    cats: ["cs.LG", "cs.CV", "stat.ML"],
    patterns: [
      "\\bdiffusion (model|probabilistic|transformer|process)",
      "\\bdenoising diffusion\\b",
      "\\bgenerative adversarial\\b",
      "\\bGANs?\\b",
      "\\bvariational autoencoder",
      "\\bVAEs?\\b",
      "\\bflow matching\\b",
      "\\bnormali[sz]ing flows?\\b",
      "\\bscore-based\\b",
    ],
    query: "diffusion model",
  },
  {
    id: "graph-learning",
    label: "Graph learning",
    field: "ai-ml",
    description:
      "Neural networks on graphs: message passing, node and link prediction, graph transformers, and knowledge graphs.",
    cats: ["cs.LG", "cs.SI"],
    patterns: [
      "\\bgraph neural network",
      "\\bGNNs?\\b",
      "\\bmessage passing\\b",
      "\\bnode classification\\b",
      "\\blink prediction\\b",
      "\\bgraph (representation|embedding|transformer|convolution)",
    ],
    query: "graph neural network",
  },
  {
    id: "optimization",
    label: "Optimisation and training",
    field: "ai-ml",
    description:
      "How models are trained: optimisers, learning rates, convergence, loss landscapes, and training dynamics.",
    cats: ["cs.LG", "math.OC", "stat.ML"],
    patterns: [
      "\\boptimi[sz]ers?\\b",
      "\\bgradient descent\\b",
      "\\bSGD\\b",
      "\\bAdamW?\\b",
      "\\blearning rate\\b",
      "\\bconvergence (rate|analysis|guarantee)",
      "\\btraining dynamics\\b",
      "\\bloss landscape\\b",
      "\\bscaling laws?\\b",
    ],
    query: "optimization",
  },
  {
    id: "interpretability",
    label: "Interpretability",
    field: "ai-ml",
    minScore: 3,
    description:
      "Understanding what models compute: explanations, attribution, probing, mechanistic analysis, and sparse features.",
    cats: ["cs.LG", "cs.AI", "cs.CL"],
    patterns: [
      "\\binterpretab",
      "\\bexplainab",
      "\\bexplanations?\\b",
      "\\bsaliency\\b",
      "\\bmechanistic\\b",
      "\\bfeature attribution\\b",
      "\\bprobing\\b",
      "\\bsparse autoencoders?\\b",
    ],
    query: "interpretability",
  },
  {
    id: "ai-safety",
    label: "Safety and alignment",
    field: "ai-ml",
    minScore: 3,
    description:
      "Making models behave: alignment, RLHF, jailbreaks, adversarial attacks, hallucination, and misuse prevention.",
    cats: ["cs.AI", "cs.LG", "cs.CL", "cs.CR"],
    patterns: [
      "\\balignment\\b",
      "\\bRLHF\\b",
      "\\bjailbreak",
      "\\bred[- ]team",
      "\\bharmful\\b",
      "\\bsafety\\b",
      "\\bhallucinat",
      "\\badversarial (attack|example|robustness|perturbation)",
      "\\bbackdoor\\b",
      "\\bwatermark",
    ],
    query: "alignment",
  },
  {
    id: "privacy-federated",
    label: "Privacy and federated learning",
    field: "ai-ml",
    description:
      "Learning without exposing data: federated training, differential privacy, membership inference, and unlearning.",
    cats: ["cs.LG", "cs.CR"],
    patterns: [
      "\\bfederated\\b",
      "\\bdifferential(ly)? privat",
      "\\bprivacy[- ]preserving\\b",
      "\\bmembership inference\\b",
      "\\bunlearning\\b",
    ],
    query: "federated learning",
  },
  {
    id: "multimodal",
    label: "Multimodal learning",
    field: "ai-ml",
    description:
      "Models that combine images, text, audio, or video: vision-language models, CLIP-style alignment, and visual question answering.",
    cats: ["cs.CV", "cs.CL", "cs.LG"],
    patterns: [
      "\\bmulti-?modal\\b",
      "\\bvision[- ]language\\b",
      "\\bVLMs?\\b",
      "\\bCLIP\\b",
      "\\bimage[- ]text\\b",
      "\\bvisual question answering\\b",
      "\\bVQA\\b",
    ],
    query: "multimodal",
  },
  {
    id: "efficient-ml",
    label: "Efficient models",
    field: "ai-ml",
    gated: true,
    description:
      "Making models cheaper: quantisation, pruning, distillation, low-rank adapters, mixture of experts, and faster inference.",
    cats: ["cs.LG", "cs.CL", "cs.CV", "cs.AI", "cs.AR"],
    patterns: [
      "\\bquantiz",
      "\\bpruning\\b",
      "\\bdistillation\\b",
      "\\bsparse (attention|activation|models?)\\b",
      "\\blow[- ]rank\\b",
      "\\bLoRA\\b",
      "\\bparameter[- ]efficient\\b",
      "\\binference (latency|speed|cost|efficien)",
      "\\bKV cache\\b",
      "\\bmixture[- ]of[- ]experts\\b",
      "\\bMoE\\b",
    ],
    query: "efficient",
  },
  {
    id: "self-supervised",
    label: "Self-supervised learning",
    field: "ai-ml",
    description:
      "Learning representations without labels: contrastive objectives, masked prediction, and large-scale pretraining.",
    cats: ["cs.LG", "cs.CV"],
    patterns: [
      "\\bself-supervised\\b",
      "\\bcontrastive\\b",
      "\\brepresentation learning\\b",
      "\\bmasked (image|autoencod|language) model",
      "\\bpre-?training objectives?\\b",
    ],
    query: "self-supervised",
  },
  {
    id: "time-series",
    label: "Time series",
    field: "ai-ml",
    description:
      "Forecasting and modelling sequences over time, including anomaly detection in streams of measurements.",
    cats: ["cs.LG", "stat.ML"],
    patterns: [
      "\\btime[- ]series\\b",
      "\\bforecasting\\b",
      "\\bsequential data\\b",
      "\\banomaly detection\\b",
      "\\btemporal (data|patterns?|dependencies)\\b",
    ],
    query: "time series",
  },
  {
    id: "benchmarks",
    label: "Benchmarks and datasets",
    field: "ai-ml",
    minScore: 3,
    description:
      "Papers whose main contribution is a new benchmark, dataset, leaderboard, or evaluation protocol.",
    cats: ["cs.LG", "cs.CL", "cs.CV"],
    patterns: [
      "\\bbenchmark",
      "\\bleaderboard\\b",
      "\\bevaluation (framework|suite|protocol|metrics?)\\b",
      "\\bwe (introduce|present|release|propose) (a |an )?(new |novel |large[- ]scale )?(dataset|corpus)\\b",
    ],
    query: "benchmark",
  },
  {
    id: "neuromorphic",
    label: "Neuromorphic and evolutionary",
    field: "ai-ml",
    description:
      "Spiking neural networks, neuromorphic hardware, and evolutionary or genetic algorithms.",
    cats: ["cs.NE"],
    patterns: [
      "\\bspiking neural\\b",
      "\\bSNNs?\\b",
      "\\bneuromorphic\\b",
      "\\bevolutionary (algorithm|computation|strateg)",
      "\\bgenetic algorithm",
      "\\bneuroevolution\\b",
    ],
    query: "spiking",
  },

  // Language & NLP --------------------------------------------------------
  {
    id: "machine-translation",
    label: "Machine translation",
    field: "nlp",
    description: "Translating text between languages and measuring translation quality.",
    cats: ["cs.CL"],
    patterns: [
      "\\bmachine translation\\b",
      "\\bneural machine translation\\b",
      "\\bNMT\\b",
      "\\btranslation (quality|model|system)s?\\b",
    ],
    query: "machine translation",
  },
  {
    id: "question-answering",
    label: "Question answering",
    field: "nlp",
    description: "Answering questions from text, tables, or knowledge, including reading comprehension.",
    cats: ["cs.CL"],
    patterns: [
      "\\bquestion answering\\b",
      "\\bQA\\b",
      "\\breading comprehension\\b",
      "\\bopen-domain question",
    ],
    query: "question answering",
  },
  {
    id: "retrieval",
    label: "Retrieval and RAG",
    field: "nlp",
    description:
      "Finding relevant documents and feeding them to a model: dense retrieval, re-ranking, embeddings, and retrieval-augmented generation.",
    cats: ["cs.CL", "cs.IR"],
    patterns: [
      "\\bretrieval[- ]augmented\\b",
      "\\bRAG\\b",
      "\\bdense retrieval\\b",
      "\\b(information|passage|document) retrieval\\b",
      "\\bre-?rank",
      "\\bembedding models?\\b",
      "\\bsemantic search\\b",
    ],
    query: "retrieval",
  },
  {
    id: "summarization",
    label: "Summarisation",
    field: "nlp",
    description: "Condensing documents, conversations, or collections into shorter summaries.",
    cats: ["cs.CL"],
    patterns: ["\\bsummari[sz]ation\\b", "\\bsummar(y|ies)\\b", "\\babstractive\\b"],
    query: "summarization",
  },
  {
    id: "speech",
    label: "Speech and audio",
    field: "nlp",
    gated: true,
    description: "Speech recognition, text-to-speech, spoken language understanding, and audio modelling.",
    cats: ["cs.CL", "cs.SD", "eess.AS"],
    patterns: [
      "\\bspeech\\b",
      "\\bASR\\b",
      "\\btext-to-speech\\b",
      "\\bTTS\\b",
      "\\bspoken\\b",
      "\\baudio\\b",
      "\\bvoice\\b",
    ],
    query: "speech",
  },
  {
    id: "dialogue",
    label: "Dialogue systems",
    field: "nlp",
    description: "Conversational agents and chatbots, multi-turn dialogue, and task-oriented assistants.",
    cats: ["cs.CL"],
    patterns: [
      "\\bdialog(ue)?\\b",
      "\\bconversational\\b",
      "\\bchatbots?\\b",
      "\\bmulti-turn\\b",
      "\\btask-oriented\\b",
    ],
    query: "dialogue",
  },
  {
    id: "sentiment-classification",
    label: "Sentiment and classification",
    field: "nlp",
    description: "Classifying text: sentiment, emotion, stance, toxicity, and topic labels.",
    cats: ["cs.CL"],
    patterns: [
      "\\bsentiment\\b",
      "\\btext classification\\b",
      "\\bemotion (recognition|detection|classification)\\b",
      "\\bstance\\b",
      "\\bhate speech\\b",
      "\\btoxic",
    ],
    query: "sentiment",
  },
  {
    id: "information-extraction",
    label: "Information extraction",
    field: "nlp",
    description: "Pulling structure out of text: named entities, relations, events, and knowledge graphs.",
    cats: ["cs.CL", "cs.IR"],
    patterns: [
      "\\bnamed entit",
      "\\bNER\\b",
      "\\brelation extraction\\b",
      "\\bentity linking\\b",
      "\\binformation extraction\\b",
      "\\bknowledge graphs?\\b",
      "\\bevent extraction\\b",
    ],
    query: "information extraction",
  },
  {
    id: "multilingual",
    label: "Multilingual and low-resource",
    field: "nlp",
    description: "Models and data for many languages, cross-lingual transfer, and languages with little training data.",
    cats: ["cs.CL"],
    patterns: ["\\bmultilingual\\b", "\\bcross-lingual\\b", "\\blow-resource\\b", "\\bcode-switch"],
    query: "multilingual",
  },
  {
    id: "code-generation",
    label: "Code and software",
    field: "nlp",
    description: "Models that write, complete, repair, or reason about source code.",
    cats: ["cs.CL", "cs.SE"],
    patterns: [
      "\\bcode generation\\b",
      "\\bprogram synthesis\\b",
      "\\bsoftware engineering\\b",
      "\\bsource code\\b",
      "\\bcode (LLMs?|models?|completion|repair)\\b",
      "\\bprogramming\\b",
    ],
    query: "code generation",
  },

  // Computer Vision ------------------------------------------------------
  {
    id: "detection-segmentation",
    label: "Detection and segmentation",
    field: "vision",
    description: "Finding and outlining objects in images: detectors, instance and semantic segmentation.",
    cats: ["cs.CV"],
    patterns: [
      "\\bobject detection\\b",
      "\\bdetectors?\\b",
      "\\bYOLO\\b",
      "\\bsegmentation\\b",
      "\\bsegment anything\\b",
      "\\bbounding box",
    ],
    query: "object detection",
  },
  {
    id: "3d-vision",
    label: "3D vision",
    field: "vision",
    description: "Recovering 3D structure: reconstruction, depth, point clouds, NeRFs, Gaussian splatting, and pose.",
    cats: ["cs.CV", "cs.GR"],
    patterns: [
      "\\b3D (reconstruction|scenes?|shapes?|geometry|vision|objects?|points?|humans?|generation|models?|representations?)\\b",
      "\\bNeRFs?\\b",
      "\\bneural radiance\\b",
      "\\bGaussian splatting\\b",
      "\\bpoint clouds?\\b",
      "\\bdepth estimation\\b",
      "\\bmulti-view\\b",
      "\\bpose estimation\\b",
    ],
    query: "3D reconstruction",
  },
  {
    id: "video",
    label: "Video understanding",
    field: "vision",
    gated: true,
    description: "Models for video: action recognition, tracking, temporal reasoning, and video generation.",
    cats: ["cs.CV"],
    patterns: ["\\bvideos?\\b", "\\baction recognition\\b", "\\bobject tracking\\b", "\\bvideo (understanding|generation|models?)\\b"],
    query: "video",
  },
  {
    id: "image-generation",
    label: "Image generation and editing",
    field: "vision",
    gated: true,
    description: "Creating and editing images: text-to-image, inpainting, super-resolution, and restoration.",
    cats: ["cs.CV", "cs.GR"],
    patterns: [
      "\\btext-to-image\\b",
      "\\bimage (generation|synthesis|editing|inpainting|restoration)\\b",
      "\\bStable Diffusion\\b",
      "\\bsuper-?resolution\\b",
      "\\bdenoising\\b",
    ],
    query: "text-to-image",
  },
  {
    id: "medical-imaging",
    label: "Medical imaging",
    field: "vision",
    description: "Vision for medicine: MRI, CT, X-ray, ultrasound, pathology slides, and clinical prediction from images.",
    cats: ["cs.CV", "eess.IV", "q-bio.QM"],
    patterns: [
      "\\bmedical (image|imaging)\\b",
      "\\bMRI\\b",
      "\\bCT (scans?|images?|volumes?)\\b",
      "\\bradiolog",
      "\\bhistopatholog",
      "\\bX-ray",
      "\\bultrasound\\b",
      "\\bclinical\\b",
      "\\btumou?rs?\\b",
      "\\blesions?\\b",
      "\\bcancer\\b",
      "\\bmetasta",
      "\\bpatients?\\b",
    ],
    query: "medical imaging",
  },
  {
    id: "remote-sensing",
    label: "Remote sensing",
    field: "vision",
    description: "Satellite and aerial imagery: land cover, change detection, hyperspectral and radar data.",
    cats: ["cs.CV", "eess.IV"],
    patterns: [
      "\\bremote sensing\\b",
      "\\bsatellite\\b",
      "\\baerial (image|imagery)\\b",
      "\\bhyperspectral\\b",
      "\\bearth observation\\b",
      "\\bland cover\\b",
    ],
    query: "remote sensing",
  },
  {
    id: "faces-humans",
    label: "Faces and people",
    field: "vision",
    description: "Recognising and modelling people: faces, human pose, gaze, gestures, and avatars.",
    cats: ["cs.CV"],
    patterns: [
      "\\bface (recognition|detection|verification)\\b",
      "\\bfacial\\b",
      "\\bhuman pose\\b",
      "\\bgaze\\b",
      "\\bperson re-?identification\\b",
      "\\bgesture",
      "\\bavatars?\\b",
    ],
    query: "face recognition",
  },

  // Neuroscience ---------------------------------------------------------
  {
    id: "neural-coding",
    label: "Neural coding",
    field: "neuro",
    gated: true,
    description: "How neurons represent information: population codes, tuning, receptive fields, and spike statistics.",
    cats: ["q-bio.NC"],
    patterns: [
      "\\bneural (coding|code|population)\\b",
      "\\bpopulation (activity|coding|dynamics)\\b",
      "\\btuning curves?\\b",
      "\\breceptive fields?\\b",
      "\\bspike trains?\\b",
      "\\bfiring rates?\\b",
    ],
    query: "neural coding",
  },
  {
    id: "brain-imaging",
    label: "Brain imaging",
    field: "neuro",
    gated: true,
    description: "Measuring the brain: fMRI, EEG, MEG, calcium imaging, and the analysis methods that go with them.",
    cats: ["q-bio.NC", "eess.SP"],
    patterns: [
      "\\bfMRI\\b",
      "\\bEEG\\b",
      "\\bMEG\\b",
      "\\bneuroimaging\\b",
      "\\bcalcium imaging\\b",
      "\\bBOLD\\b",
    ],
    query: "fMRI",
  },
  {
    id: "neuron-models",
    label: "Neuron and circuit models",
    field: "neuro",
    gated: true,
    description: "Mathematical models of neurons and circuits: biophysical models, attractors, mean-field and network dynamics.",
    cats: ["q-bio.NC", "nlin.AO"],
    patterns: [
      "\\bHodgkin-Huxley\\b",
      "\\bintegrate-and-fire\\b",
      "\\bbiophysical model",
      "\\bneural mass\\b",
      "\\bmean[- ]field\\b",
      "\\battractors?\\b",
      "\\bcortical (circuits?|models?|columns?)\\b",
      "\\bdendrit",
      "\\bcriticality\\b",
      "\\bmodels? of (real |single |cortical )?neurons\\b",
    ],
    query: "neuron model",
  },
  {
    id: "brain-computer-interfaces",
    label: "Brain-computer interfaces",
    field: "neuro",
    gated: true,
    description: "Decoding intent from neural signals to control devices, restore speech or movement, and give feedback.",
    cats: ["q-bio.NC", "cs.HC"],
    patterns: [
      "\\bbrain[- ]computer interface",
      "\\bBCIs?\\b",
      "\\bneural decoding\\b",
      "\\bneuroprosthe",
      "\\bintracortical\\b",
      "\\bneurofeedback\\b",
    ],
    query: "brain-computer interface",
  },
  {
    id: "learning-memory",
    label: "Learning and memory",
    field: "neuro",
    gated: true,
    description: "Plasticity, memory formation and recall, hippocampal function, and biological learning rules.",
    cats: ["q-bio.NC"],
    patterns: [
      "\\bplasticity\\b",
      "\\bmemory (consolidation|formation|retrieval|recall)\\b",
      "\\bhippocamp",
      "\\bworking memory\\b",
      "\\blearning rules?\\b",
      "\\bHebbian\\b",
      "\\breplay\\b",
      "\\bengrams?\\b",
    ],
    query: "synaptic plasticity",
  },
  {
    id: "connectomics",
    label: "Connectivity and networks",
    field: "neuro",
    gated: true,
    description: "Wiring of the brain: connectomes, functional and structural connectivity, and network analysis.",
    cats: ["q-bio.NC"],
    patterns: [
      "\\bconnectom",
      "\\b(functional|structural|effective) connectivity\\b",
      "\\bbrain networks?\\b",
      "\\bwhite matter\\b",
      "\\btractograph",
    ],
    query: "connectivity",
  },
  {
    id: "neuro-ai",
    label: "Brains and machines",
    field: "neuro",
    gated: true,
    description: "Where neuroscience meets AI: brain-inspired models, comparing deep networks with the brain, predictive coding.",
    cats: ["q-bio.NC", "cs.NE", "cs.AI"],
    patterns: [
      "\\bbrain-inspired\\b",
      "\\bbiologically plausible\\b",
      "\\bneural network models? of\\b",
      "\\brepresentational similarity\\b",
      "\\bventral stream\\b",
      "\\bpredictive coding\\b",
      "\\bvisual cortex\\b",
    ],
    query: "brain-inspired",
  },
  {
    id: "cognition-behaviour",
    label: "Cognition and behaviour",
    field: "neuro",
    gated: true,
    description: "Decision making, perception, and behaviour in humans and animals, and the neural processes behind them.",
    cats: ["q-bio.NC"],
    patterns: [
      "\\bdecision[- ]making\\b",
      "\\bbehavio(u)?ral (tasks?|data|experiments?)\\b",
      "\\bpsychophysic",
      "\\bcognition\\b",
      "\\bcognitive (control|maps?|tasks?|neuroscience|load|processes)\\b",
      "\\b(mice|rodents?|monkeys?|primates?)\\b",
      "\\bhuman participants\\b",
    ],
    query: "decision making",
  },

  // Statistics & ML theory ------------------------------------------------
  {
    id: "bayesian",
    label: "Bayesian methods",
    field: "stats",
    description: "Probabilistic modelling and inference: priors and posteriors, MCMC, variational inference, Gaussian processes.",
    cats: ["stat.ML", "stat.ME", "stat.CO"],
    patterns: [
      "\\bBayesian\\b",
      "\\bposterior\\b",
      "\\bMCMC\\b",
      "\\bMarkov chain Monte Carlo\\b",
      "\\bvariational inference\\b",
      "\\bGaussian process",
      "\\bprobabilistic (model|programming)",
    ],
    query: "Bayesian",
  },
  {
    id: "causal-inference",
    label: "Causal inference",
    field: "stats",
    description: "Estimating cause and effect: treatment effects, confounding, instrumental variables, structural causal models.",
    cats: ["stat.ME", "stat.ML", "econ.EM"],
    patterns: [
      "\\bcausal\\b",
      "\\bcounterfactual(?! regret)",
      "\\btreatment effects?\\b",
      "\\binstrumental variable",
      "\\bconfound",
      "\\bpropensity\\b",
    ],
    query: "causal",
  },
  {
    id: "high-dimensional",
    label: "High-dimensional statistics",
    field: "stats",
    description: "Estimation when there are more variables than samples: sparsity, LASSO, minimax rates, random matrices.",
    cats: ["math.ST", "stat.ML"],
    patterns: [
      "\\bhigh[- ]dimensional\\b",
      "\\bsparse (regression|recovery|estimation)\\b",
      "\\bLASSO\\b",
      "\\bminimax\\b",
      "\\bcovariance (estimation|matri)",
      "\\bcompressed sensing\\b",
      "\\brandom matri",
    ],
    query: "high-dimensional",
  },
  {
    id: "hypothesis-testing",
    label: "Hypothesis testing",
    field: "stats",
    description: "Tests, p-values, confidence sets, multiple testing, and false discovery control.",
    cats: ["math.ST", "stat.ME"],
    patterns: [
      "\\bhypothesis test",
      "\\bp-values?\\b",
      "\\bmultiple testing\\b",
      "\\bfalse discovery\\b",
      "\\bconfidence (intervals?|sets?)\\b",
      "\\btwo-sample\\b",
      "\\bgoodness[- ]of[- ]fit\\b",
      "\\bpermutation test",
    ],
    query: "hypothesis testing",
  },
  {
    id: "learning-theory",
    label: "Learning theory",
    field: "stats",
    description: "Why learning works: generalisation bounds, sample complexity, kernels, overparameterisation, and implicit bias.",
    cats: ["stat.ML", "cs.LG", "math.ST"],
    patterns: [
      "\\bgenerali[sz]ation (bounds?|error|gap|analysis|guarantees?)\\b",
      "\\bsample complexity\\b",
      "\\bPAC\\b",
      "\\bRademacher\\b",
      "\\bkernel[- ](methods?|regression|ridge|based)\\b",
      "\\bexcess risk\\b",
      "\\bimplicit (bias|regulari)",
      "\\boverparameteri[sz]",
      "\\bdouble descent\\b",
      "\\bneural tangent\\b",
    ],
    query: "generalization",
  },
  {
    id: "uncertainty",
    label: "Uncertainty and robustness",
    field: "stats",
    description: "Knowing when a model is unsure: calibration, conformal prediction, ensembles, and distribution shift.",
    cats: ["stat.ML", "cs.LG"],
    patterns: [
      "\\bconformal\\b",
      "\\bcalibrat",
      "\\buncertainty (quantification|estimat)",
      "\\bprediction (intervals?|sets?)\\b",
      "\\bensembles?\\b",
      "\\bout-of-distribution\\b",
      "\\bOOD\\b",
      "\\bdistribution shift\\b",
    ],
    query: "uncertainty",
  },
  {
    id: "optimal-transport",
    label: "Optimal transport",
    field: "stats",
    description: "Comparing and moving probability distributions: Wasserstein distances, Sinkhorn, and their uses in learning.",
    cats: ["stat.ML", "math.OC", "math.PR"],
    patterns: ["\\boptimal transport\\b", "\\bWasserstein\\b", "\\bSinkhorn\\b"],
    query: "optimal transport",
  },

  // Robotics -------------------------------------------------------------
  {
    id: "manipulation",
    label: "Manipulation",
    field: "robotics",
    description: "Robots handling objects: grasping, dexterous hands, pick-and-place, tactile sensing, and assembly.",
    cats: ["cs.RO"],
    patterns: [
      "\\bmanipulat",
      "\\bgrasp",
      "\\bdexterous\\b",
      "\\bpick[- ]and[- ]place\\b",
      "\\brobot(ic)? arms?\\b",
      "\\btactile\\b",
      "\\bdeformable objects?\\b",
    ],
    query: "manipulation",
  },
  {
    id: "locomotion",
    label: "Locomotion",
    field: "robotics",
    gated: true,
    description: "Legged and humanoid robots: gaits, balance, walking and running controllers, exoskeletons.",
    cats: ["cs.RO"],
    patterns: [
      "\\blocomotion\\b",
      "\\blegged\\b",
      "\\bquadruped",
      "\\bhumanoid",
      "\\bbiped",
      "\\bgaits?\\b",
      "\\bexoskeleton",
    ],
    query: "locomotion",
  },
  {
    id: "navigation",
    label: "Navigation and SLAM",
    field: "robotics",
    gated: true,
    description: "Knowing where the robot is and how to get somewhere: localisation, mapping, SLAM, and path planning.",
    cats: ["cs.RO"],
    patterns: [
      "\\bSLAM\\b",
      "\\bnavigation\\b",
      "\\blocali[sz]ation\\b",
      "\\bmapping\\b",
      "\\bpath planning\\b",
      "\\bmotion planning\\b",
      "\\bodometry\\b",
      "\\bobstacle avoidance\\b",
    ],
    query: "navigation",
  },
  {
    id: "autonomous-driving",
    label: "Autonomous driving",
    field: "robotics",
    gated: true,
    description: "Self-driving vehicles: perception with cameras and LiDAR, prediction, planning, and traffic scenarios.",
    cats: ["cs.RO", "cs.CV"],
    patterns: [
      "\\bautonomous (driving|vehicles?)\\b",
      "\\bself-driving\\b",
      "\\bdriving (scenarios?|polic|datasets?)\\b",
      "\\bLiDAR\\b",
      "\\btraffic\\b",
      "\\bpedestrians?\\b",
    ],
    query: "autonomous driving",
  },
  {
    id: "aerial-robotics",
    label: "Drones and aerial robots",
    field: "robotics",
    description: "Flying robots: quadrotors and other UAVs, aerial perception, flight control, and swarms in the air.",
    cats: ["cs.RO"],
    patterns: [
      "\\bdrones?\\b",
      "\\bUAVs?\\b",
      "\\bquadrotor",
      "\\bquadcopter",
      "\\baerial (robots?|vehicles?)\\b",
      "\\bflight\\b",
    ],
    query: "UAV",
  },
  {
    id: "human-robot-interaction",
    label: "Human-robot interaction",
    field: "robotics",
    description: "Robots working with or for people: collaboration, teleoperation, social and assistive robots, haptics.",
    cats: ["cs.RO", "cs.HC"],
    patterns: [
      "\\bhuman[- ]robot\\b",
      "\\bHRI\\b",
      "\\bteleoperat",
      "\\bsocial robots?\\b",
      "\\bassistive\\b",
      "\\bcollaborative robots?\\b",
      "\\bshared autonomy\\b",
      "\\bhaptic",
    ],
    query: "human-robot interaction",
  },
  {
    id: "robot-learning",
    label: "Robot learning",
    field: "robotics",
    description: "Learning robot skills from data: imitation learning, sim-to-real transfer, visuomotor policies, vision-language-action models.",
    cats: ["cs.RO", "cs.LG"],
    patterns: [
      "\\bimitation learning\\b",
      "\\bsim-?to-?real\\b",
      "\\bsim2real\\b",
      "\\bbehavio(u)?r cloning\\b",
      "\\bvisuomotor\\b",
      "\\brobot (learning|polic)",
      "\\b(human|expert|from) demonstrations?\\b",
      "\\bvision-language-action\\b",
      "\\bVLA\\b",
      "\\bdiffusion polic",
    ],
    query: "imitation learning",
  },
  {
    id: "control",
    label: "Control and planning",
    field: "robotics",
    description: "Classical and learned control: model predictive control, trajectory optimisation, stability, and safety constraints.",
    cats: ["cs.RO", "eess.SY", "math.OC"],
    patterns: [
      "\\bmodel predictive control\\b",
      "\\bMPC\\b",
      "\\btrajectory optimi[sz]ation\\b",
      "\\boptimal control\\b",
      "\\bcontrol (barrier|Lyapunov)\\b",
      "\\bcontrollers?\\b",
      "\\bfeedback control\\b",
    ],
    query: "model predictive control",
  },
  {
    id: "multi-robot",
    label: "Multi-robot systems",
    field: "robotics",
    description: "Teams and swarms of robots: coordination, formation control, task allocation, and fleet management.",
    cats: ["cs.RO", "cs.MA"],
    patterns: ["\\bmulti-?robot\\b", "\\bswarms?\\b", "\\bfleets?\\b", "\\bformation control\\b", "\\btask allocation\\b"],
    query: "multi-robot",
  },
];

const byId = new Map(TOPICS.map((t) => [t.id, t]));

export function topicById(id: string): Topic | undefined {
  return byId.get(id);
}

/** Topics that belong to a field, in taxonomy order. */
export function topicsForField(fieldId: string): Topic[] {
  return TOPICS.filter((t) => t.field === fieldId);
}

/** Field ids that have at least one topic. Used by the taxonomy test. */
export const FIELD_IDS = new Set(FIELDS.map((f) => f.id));
